# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Ihor Shevchuk
name: Build
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  Build:
    runs-on: macos-latest
    env:
      CI_BUILD: "1"
      BUILD_OUTPUT: "${{ github.workspace }}/BuildOutput"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true 
          submodules: false

      - name: Setup Mise
        uses: jdx/mise-action@v2

      - name: Set Build Number
        run: |
          echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          # Extract version for logging only
          source PiperApp/BuildScripts/Configs/version.xcconfig
          echo "Full Version: $MARKETING_VERSION($GITHUB_RUN_NUMBER)"
        shell: bash

      - name: Install Apple Signing Assets
        if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          APP_PROVISION_PROFILE_BASE64: ${{ secrets.APP_PROVISION_PROFILE_BASE64 }}
          EXT_PROVISION_PROFILE_BASE64: ${{ secrets.EXT_PROVISION_PROFILE_BASE64 }}
          APPLE_WWDRCAG3_BASE64: ${{ secrets.APPLE_WWDRCAG3 }}
        run: |     
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # Import assets to temporary keychain
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $RUNNER_TEMP/cert.p12
          echo -n "$APPLE_WWDRCAG3_BASE64" | base64 --decode -o $RUNNER_TEMP/wwdr.cer
          
          security create-keychain -p "$P12_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$P12_PASSWORD" $KEYCHAIN_PATH
          security import $RUNNER_TEMP/cert.p12 -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $RUNNER_TEMP/wwdr.cer -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply provisioning profiles
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "$APP_PROVISION_PROFILE_BASE64" | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/app.mobileprovision
          echo -n "$EXT_PROVISION_PROFILE_BASE64" | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/ext.mobileprovision

      - name: Prepare Project
        run: |
          mise run lfs
          rm -fr *.xcodeproj | echo "Failed to remove project"
          rm -fr *.xcworkspace | echo "Failed to remove workspace"
          mise run generate

      - name: Build
        run: |
          TARGET=${{ github.event_name == 'push' && 'device' || 'simulator' }}
          mise run build $BUILD_NUMBER $TARGET

      - name: Store IPA
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: Piper-Build-${{ env.BUILD_NUMBER }}
          path: ${{ env.BUILD_OUTPUT }}/binary/iOS/Piper.ipa
          retention-days: 7

      - name: Clean up
        if: ${{ always() }}
        run: |
          echo "Keychains before removing temp keychain"
          security list-keychains | echo "Failed to list keychains"
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          security lock-keychain $KEYCHAIN_PATH | echo "Failed to lock keychain at path $KEYCHAIN_PATH"
          security delete-keychain $KEYCHAIN_PATH | echo "Failed to delete keychain at path $KEYCHAIN_PATH"
          echo "Keychains after removing temp keychain"
          security list-keychains | echo "Failed to list keychains"
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision | echo "Failed to remove provision profile"
          rm $RUNNER_TEMP/$FASTLANE_CONFIG_NAME | echo "Failed to remove fastlane config"
          rm ~/.gitconfig | echo "Failed to remove ~/.gitconfig"
          rm ~/.ssh/key-* | echo "Failed to clean ssh keys"